#!/bin/sh
PIDFILE_JPG="/var/run/start-jpg.pid"
PIDFILE_MQTT="/var/run/start-mqtt.pid"

status()
{
  pid_1="$(cat "$PIDFILE_JPG" 2>/dev/null)"
  pid_2="$(cat "$PIDFILE_MQTT" 2>/dev/null)"
  if [ "$pid_1" ]; then
    kill -0 "$pid_1" >/dev/null && kill -0 "$pid_1" >/dev/null && echo "PID: $pid_1,$pid_2" || return 1
  fi
}

start()
{
  echo "Starting Snapshot script..."
  start-jpg.sh </dev/null >/dev/null 2>&1 &
  echo "$!" > "$PIDFILE_JPG"
  start-mqtt.sh </dev/null >/dev/null 2>&1 &
  echo "$!" > "$PIDFILE_MQTT"
}

stop()
{
  pid="$(cat "$PIDFILE_JPG" 2>/dev/null)"
  if [ "$pid" ]; then
     pkill -9 -P $pid || rm "$PIDFILE_JPG"
  fi
  pid="$(cat "$PIDFILE_MQTT" 2>/dev/null)"
  if [ "$pid" ]; then
     pkill -9 -P $pid || rm "$PIDFILE_MQTT"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
